apiVersion: v1
kind: Secret
metadata:
  name: ncs-app-secrets
  namespace: ${NAMESPACE}
type: Opaque
data:

  #HWC
  aws_access_key_id: ${HWC_ACCESS_KEY}
  aws_secret_access_key: ${HWC_SECRET_KEY}

  # RabbitMQ
  rabbit_username: ${RABBIT_USER}
  rabbit_password: ${RABBIT_PASS}
  rabbit_host: ${RABBIT_HOST}
  rabbit_virtual_host: ${RABBIT_VIRTUAL_HOST} 
 