apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndp-ingestion
  namespace: ${NAMESPACE}
  labels:
    app: ndp-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ndp-ingestion
  template:
    metadata:
      labels:
        app: ndp-ingestion
    spec:
      imagePullSecrets: 
      - name: acrprdng011920179-auth
      containers:
        - name: ndp-ingestion
          image: acrprdng01.azurecr.io/dataplatform-ndp-ingestion:${CI_COMMIT_SHORT_SHA}
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: ${LOCAL_TEMP_FOLDER}
            name: temp-files
          command: ["python"]
          args: ["src/process.py"]
          envFrom:
            - secretRef:
                name: ndp-app-secrets
            - configMapRef:
                name: ndp-app-vars
          ports:
            - containerPort: 8079
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
      volumes:
      - name: temp-files
        persistentVolumeClaim:
          claimName: pvc-ndp-ingestion-data