apiVersion: v1
data:
  access.key: ${HWC_ACCESS_KEY}
  secret.key: ${HWC_SECRET_KEY}
kind: Secret
metadata:
  name: ndp-obs-user
  namespace: ${NAMESPACE}
  labels:
    secret.kubernetes.io/used-by: csi
type: cfe/secure-opaque