kind: Secret
apiVersion: v1
metadata:
  name: acrprdng011920179-auth
  namespace: dataplatform-ingestion
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJhY3JwcmRuZzAxLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJmNzgzMTRjMy05YjRjLTQ4OTQtODY1MC1jNThjYzk5YzA5MTkiLCJwYXNzd29yZCI6IkdFUThRfmlNN2JvSmNXZUs5ZkIuOHRJdmJYNFhwR2RVNGNScFFifkIiLCJlbWFpbCI6IlNlcnZpY2VQcmluY2lwYWxAQXp1cmVSTSIsImF1dGgiOiJaamM0TXpFMFl6TXRPV0kwWXkwME9EazBMVGcyTlRBdFl6VTRZMk01T1dNd09URTVPa2RGVVRoUmZtbE5OMkp2U21OWFpVczVaa0l1T0hSSmRtSllORmh3UjJSVk5HTlNjRkZpZmtJPSJ9fX0=
type: kubernetes.io/dockerconfigjson