apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: everest-csi-provisioner
  name: pv-ndp-ingestion-data
  labels: {}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  mountOptions:  
  - default_acl=bucket-owner-full-control    
  csi:
    driver: obs.csi.everest.io
    fsType: obsfs
    volumeHandle: ${BUCKET_PV_NAME}
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: everest-csi-provisioner
      everest.io/region: la-south-2
    nodePublishSecretRef:
      name: ndp-obs-user
      namespace: ${NAMESPACE}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-obs
